wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
num_classes:
  desc: null
  value: 1
steps_per_epoch:
  desc: null
  value: 772
epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.12.5
    cli_version: 0.17.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1737132649
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.12.5
      5: 0.17.9
      8:
      - 5
      13: linux-x86_64
